"""Engine optimization parity guard (Batch 307+).

Source: per CHECKLIST #77 canonical-source attribution. Before any
optimization batch (308 pre-compute features, 309 skip unused signals,
310 vectorized screener) ships, this test must pass:

  Hypothesis: optimization preserves signal semantics exactly.
  Method: run engine on a fixed 5-tkr x 6-month deterministic window;
          compare every trade-log row to a golden snapshot.
  Pass: byte-identical for non-float columns + float-tolerance (1e-9
        relative) for derived metrics.

The golden snapshot is generated by the FIRST run of this test (it
saves to backtest/tests/fixtures/engine_parity_golden.csv). After that,
every subsequent run compares against the saved golden. Update the
golden ONLY when intentional behavior changes land (engine semantics
change, not optimization).

Per L155 / CHECKLIST #83: optimization is a kind of "data layer
migration" - changes how the engine computes signal values. Same
silent-gap risk class as the prior 6 bugs. This parity test is the
correctness gate.

Run:
  pytest backtest/tests/test_engine_optimization_parity.py -v

Update golden (only after intentional semantic change):
  pytest backtest/tests/test_engine_optimization_parity.py -v --update-golden
"""
from __future__ import annotations

import os
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

REPO = Path(__file__).resolve().parent.parent.parent
FIXTURES_DIR = REPO / "backtest" / "tests" / "fixtures"
FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
GOLDEN_PATH = FIXTURES_DIR / "engine_parity_golden.csv"

# Deterministic 5-tkr mega-cap sample. ALL must have Polygon ref + OHLCV
# coverage in 2023 H2. If any drops out of cache later, this test will
# skip with a clear message (not silently change semantics).
PARITY_TICKERS = ["AAPL", "MSFT", "NVDA", "GOOGL", "AMZN"]
PARITY_START = date(2023, 7, 1)
PARITY_END = date(2023, 12, 31)
PARITY_OUTPUT_DIR = REPO / "output_parity_tmp"

# Columns compared by exact equality (string/categorical)
EXACT_COLS = [
    "ticker", "entry_date", "exit_date", "direction", "strategy",
    "category", "sector", "confidence_tier", "regime", "exit_reason",
    "win", "trade_id",
]
# Columns compared with float tolerance
TOL_COLS = [
    "entry_price", "exit_price", "initial_stop", "highest_close",
    "trailing_stop_at_exit", "pnl_pct", "pnl_dollar", "hold_days",
    "max_adverse_excursion", "max_favourable_excursion",
]
# Float tolerance: 1e-6 relative + 1e-9 absolute (looser than 1e-9 for
# slippage/cost computations that round to cents)
FLOAT_RTOL = 1e-6
FLOAT_ATOL = 1e-9


def _run_engine_parity():
    """Run the engine on the parity scenario via the full CLI pipeline so
    the writer fires (trade_log.csv is written by run_phase1a.py, not by
    BacktestEngine.run() directly). Returns the trade_log DataFrame."""
    import subprocess
    import sys

    PARITY_OUTPUT_DIR.mkdir(exist_ok=True)
    tickers_csv = ",".join(PARITY_TICKERS)
    cmd = [
        sys.executable, "-m", "backtest.run_phase1a",
        "--phase", "1a-beta",
        "--no-agents",
        "--no-git",
        "--no-walk-forward",
        "--tickers", tickers_csv,
        "--start", PARITY_START.isoformat(),
        "--end", PARITY_END.isoformat(),
        "--output-dir", str(PARITY_OUTPUT_DIR),
    ]
    rc = subprocess.call(cmd, cwd=str(REPO))
    if rc != 0:
        pytest.fail(f"run_phase1a CLI returned rc={rc}")

    tl_path = PARITY_OUTPUT_DIR / "trade_log.csv"
    if not tl_path.exists():
        # Fall back to checkpoint (same trade rows, no post-processing)
        ck_path = PARITY_OUTPUT_DIR / "trade_log_checkpoint.csv"
        if ck_path.exists():
            return pd.read_csv(ck_path, low_memory=False)
        pytest.fail(f"Engine produced no trade_log at {tl_path}")
    return pd.read_csv(tl_path, low_memory=False)


def _normalize_for_compare(df: pd.DataFrame) -> pd.DataFrame:
    """Stable sort + reset index so row order is canonical."""
    sort_cols = [c for c in ("trade_id", "ticker", "entry_date", "strategy")
                 if c in df.columns]
    return df.sort_values(sort_cols).reset_index(drop=True)


def _check_parity(actual: pd.DataFrame, golden: pd.DataFrame) -> list:
    """Compare two trade_log DataFrames. Returns list of mismatch strings."""
    mismatches = []
    if len(actual) != len(golden):
        mismatches.append(
            f"row count: actual={len(actual)} vs golden={len(golden)}"
        )
        # Short-circuit; row-by-row compare is meaningless if counts differ
        return mismatches

    actual = _normalize_for_compare(actual)
    golden = _normalize_for_compare(golden)

    for col in EXACT_COLS:
        if col not in actual.columns or col not in golden.columns:
            continue
        diff = (actual[col].astype(str) != golden[col].astype(str)).sum()
        if diff > 0:
            sample = actual.loc[actual[col].astype(str) != golden[col].astype(str), col].head(3).tolist()
            golden_sample = golden.loc[actual[col].astype(str) != golden[col].astype(str), col].head(3).tolist()
            mismatches.append(
                f"col {col}: {diff} rows differ (actual {sample} vs golden {golden_sample})"
            )

    for col in TOL_COLS:
        if col not in actual.columns or col not in golden.columns:
            continue
        a = pd.to_numeric(actual[col], errors="coerce")
        g = pd.to_numeric(golden[col], errors="coerce")
        # Both NaN should match
        both_nan = a.isna() & g.isna()
        valid = ~both_nan
        if not valid.any():
            continue
        try:
            np.testing.assert_allclose(
                a[valid].values, g[valid].values,
                rtol=FLOAT_RTOL, atol=FLOAT_ATOL,
                err_msg=f"col {col} differs beyond tolerance",
            )
        except AssertionError as e:
            mismatches.append(f"col {col}: {str(e).splitlines()[0]}")

    return mismatches


@pytest.fixture(scope="session")
def parity_run():
    """Run the engine once per pytest session, share result across tests."""
    return _run_engine_parity()


def test_engine_parity_golden_exists_or_create(parity_run):
    """If golden snapshot missing, create it from this run. Otherwise compare.

    To explicitly regenerate (after intentional semantic change):
      UPDATE_GOLDEN=1 pytest backtest/tests/test_engine_optimization_parity.py
    """
    actual = parity_run
    update_requested = os.environ.get("UPDATE_GOLDEN", "0") == "1"

    if not GOLDEN_PATH.exists() or update_requested:
        actual_normalized = _normalize_for_compare(actual)
        actual_normalized.to_csv(GOLDEN_PATH, index=False)
        pytest.skip(
            f"Golden snapshot {'updated' if update_requested else 'created'} at "
            f"{GOLDEN_PATH.relative_to(REPO)} ({len(actual_normalized)} rows). "
            f"Re-run pytest to verify parity."
        )

    golden = pd.read_csv(GOLDEN_PATH, low_memory=False)
    mismatches = _check_parity(actual, golden)
    assert not mismatches, (
        f"Engine optimization parity FAILED ({len(mismatches)} mismatches):\n  "
        + "\n  ".join(mismatches)
    )


def test_engine_parity_row_count_invariant(parity_run):
    """Trade count for the parity scenario should be in a deterministic
    window. 5-tkr x 6-month mega-cap baseline produces ~10-25 trades
    empirically. Catches gross regressions even during golden updates.

    Calibration: first golden run produced 13 trades. Bound at [5, 100]
    leaves room for normal variance in exit timing while flagging
    catastrophic roster collapse (->0 trades) or runaway firing (>>25)."""
    actual = parity_run
    assert 5 <= len(actual) <= 100, (
        f"Parity scenario produced {len(actual)} trades; expected 5-100. "
        f"Either the engine's roster collapsed or it's now firing too aggressively."
    )


def test_engine_parity_pnl_sum_invariant(parity_run):
    """Total PnL sum for the parity scenario should be in a deterministic
    band. Looser bound than golden but catches catastrophic regressions.

    Calibration: first golden run had PnL sum ~+5 pp. Bound at [-50, 100]
    accommodates variance from per-trade slippage/cost rounding."""
    actual = parity_run
    if "pnl_pct" not in actual.columns:
        pytest.skip("pnl_pct column missing")
    total_pp = actual["pnl_pct"].sum()
    assert -50 <= total_pp <= 100, (
        f"Parity scenario PnL sum {total_pp:.1f}pp outside [-50, 100]. "
        f"Engine semantics likely changed beyond optimization scope."
    )


