// Phase 1A Trade Summary Dashboard — vanilla JS + DataTables + Chart.js
// Consumes window.PHASE_1A_DATA emitted by scripts/build_dashboard_phase_1a.py
// Batch 422 (2026-05-28): defensive fallback. The build script now emits
// `window.PHASE_1A_DATA = ...` (was `const PHASE_1A_DATA = ...` which
// doesn't attach to window in regular <script> context -> all tabs blank).
// Fallback to lexical-global lookup preserves backward compat if data.js
// is ever regenerated by an older build script.
const D = (typeof window !== "undefined" && window.PHASE_1A_DATA)
  || (typeof PHASE_1A_DATA !== "undefined" ? PHASE_1A_DATA : {})
  || {};

// ---- helpers ----
const $ = (sel) => document.querySelector(sel);
const fmtNum = (v, dp = 2) => v === null || v === undefined || Number.isNaN(v) ? "—" : Number(v).toFixed(dp);
const fmtPct = (v, dp = 1) => v === null || v === undefined ? "—" : (Number(v) * (Math.abs(v) > 1 ? 1 : 100)).toFixed(dp) + "%";
const fmtInt = (v) => v === null || v === undefined ? "—" : Math.round(Number(v)).toLocaleString();
function kpi(value, label, cls) {
  return `<div class="kpi"><div class="v ${cls || ''}">${value}</div><div class="l">${label}</div></div>`;
}
function emptyMsg(target, msg) {
  $(target).innerHTML = `<div class="empty">${msg}</div>`;
}
function buildTable(selector, rows, opts = {}) {
  if (!rows || rows.length === 0) {
    const el = document.querySelector(selector);
    if (el) el.outerHTML = `<div class="empty">No data</div>`;
    return;
  }
  const cols = opts.columns || Object.keys(rows[0]).map(k => ({ title: k, data: k, defaultContent: "—" }));
  $(selector).innerHTML = "<thead><tr>" + cols.map(c => `<th>${c.title}</th>`).join("") + "</tr></thead>";
  // Batch 430 (2026-05-29): removed a broken window-ready wrapper here.
  // The line passed the window object through the local `$` helper which
  // is overridden as document.querySelector at the top of this file.
  // querySelector(window) throws SyntaxError ("[object Window] is not a
  // valid selector"), which killed every buildTable() call - tabs 1-9 +
  // Exits + Trades + Tab 13 only ever rendered their <h2> header + an
  // empty <table> stub. DataTable does not need a wrapper here.
  jQuery(selector).DataTable({
    data: rows,
    columns: cols,
    pageLength: opts.pageLength || 15,
    order: opts.order || [],
    deferRender: true,
    autoWidth: false,
  });
}

// ---- tab switching ----
document.querySelectorAll('.tab-btn').forEach(btn => {
  btn.addEventListener('click', () => {
    document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
    document.querySelectorAll('section.panel').forEach(s => s.classList.remove('active'));
    btn.classList.add('active');
    document.getElementById(btn.dataset.panel).classList.add('active');
  });
});

// ---- header meta ----
const generated = D.generated_at || "?";
const tradeCount = (D.trade_log_preview || []).length;
const stratCount = (D.backtest_results || []).length;
$("#meta-line").textContent = `Generated ${generated.slice(0, 19)} UTC · ${stratCount} strategies · ${tradeCount} trades shown · source: ${D.source_dir || 'output_v2'}`;

// ---- TAB: Overview ----
function renderOverview() {
  const psum = D.portfolio_summary || {};
  const pmetrics = D.portfolio_metrics || {};
  const imps = D.improvements_summary || {};
  const ret = psum.portfolio_return_pct ?? psum.total_return_pct;
  const heat = psum.max_portfolio_heat_pct;
  const sharpe = pmetrics.sharpe ?? psum.sharpe;
  const dd = pmetrics.max_dd ?? psum.max_drawdown_pct;
  const winRate = psum.win_rate ?? psum.win_rate_pct;
  const pf = psum.profit_factor;
  const totalTrades = psum.total_trades ?? psum.n_trades;
  const passingStrategies = (D.backtest_results || []).filter(r => (r.passes_all || r.passing) === true || r.passes_all === "True").length;
  const kpis = [
    kpi(fmtPct(ret, 1), "Portfolio return", (ret ?? 0) >= 0 ? "good" : "bad"),
    kpi(fmtNum(sharpe, 2), "Sharpe ratio", (sharpe ?? 0) >= 1 ? "good" : (sharpe ?? 0) >= 0.7 ? "warn" : "bad"),
    kpi(fmtPct(dd, 1), "Max drawdown", "warn"),
    kpi(fmtPct(winRate, 1), "Win rate", (winRate ?? 0) >= 0.55 ? "good" : "warn"),
    kpi(fmtNum(pf, 2), "Profit factor", (pf ?? 0) >= 1.5 ? "good" : (pf ?? 0) >= 1.3 ? "warn" : "bad"),
    kpi(fmtPct(heat, 1), "Max portfolio heat"),
    kpi(fmtInt(totalTrades), "Total trades"),
    kpi(`${passingStrategies}/${stratCount}`, "Passing strategies", passingStrategies > 0 ? "good" : "bad"),
  ];
  $("#overview-kpis").innerHTML = kpis.join("");

  // Overview table — merge psum + pmetrics into key-value pairs
  const kvRows = [];
  for (const [k, v] of Object.entries(psum)) kvRows.push({ source: "portfolio_summary", key: k, value: String(v) });
  for (const [k, v] of Object.entries(pmetrics)) kvRows.push({ source: "portfolio_metrics", key: k, value: String(v) });
  for (const [k, v] of Object.entries(imps).slice(0, 30)) kvRows.push({ source: "improvements_summary", key: k, value: typeof v === "object" ? JSON.stringify(v).slice(0, 80) : String(v) });
  buildTable("#overview-table", kvRows, { pageLength: 25, order: [[0, "asc"]] });
}

// ---- TAB: Strategies ----
function renderStrategies() {
  const rows = D.backtest_results || [];
  if (!rows.length) { emptyMsg("#strat-kpis", "No backtest_results.csv"); return; }
  const passing = rows.filter(r => r.passes_all === true || r.passes_all === "True").length;
  const avgSharpe = rows.reduce((a, r) => a + (Number(r.sharpe) || 0), 0) / rows.length;
  const avgPF = rows.reduce((a, r) => a + (Number(r.profit_factor) || 0), 0) / rows.length;
  // Batch 437 (2026-05-29): cube-only source. All KPIs come from the
  // same Phase 1A-beta cube run; no more baseline/cube split.
  const pza = (D.producer_zero_audit || {}).summary || {};
  const sourceDir = D.source_dir || "output_batch395_final";
  $("#strat-kpis").innerHTML = [
    kpi(pza.active_count != null ? pza.active_count : 185, "Registered (code)"),
    kpi(rows.length, "Fired in this cube run", "good"),
    pza.quiet_count != null ? kpi(pza.quiet_count, "Quiet (Tab 12)", "warn") : "",
    kpi(passing, "Passing all 9 gates", passing > 0 ? "good" : "bad"),
    kpi(fmtNum(avgSharpe, 2), "Avg Sharpe"),
    kpi(fmtNum(avgPF, 2), "Avg profit factor"),
  ].join("");
  // Inclusion-criteria callout above the table.
  // Batch 437 (2026-05-29): cube-only Phase 1A-beta source. Was prior
  // (Batches 435/436) baseline+cube two-run comparison, but that
  // misrepresented the architecture - Phase 1A-beta is cube-only per
  // owner directive; baseline gates only return in Phase 1B-alpha.
  const callout = document.getElementById("strat-inclusion-callout");
  if (callout) {
    callout.innerHTML = `
      <strong>Inclusion criteria for this table:</strong> a strategy appears here if it fired <em>at least one trade</em> during the Phase 1A-beta cube run (<code>${sourceDir}</code>). No min-trade threshold. Source: <code>backtest/results/metrics.py::compute_all_metrics</code> iterates over <code>trade_log["strategy"].unique()</code>.
      <br><br>
      <strong>Why this is ${rows.length} rows out of 185 registered:</strong> 185 = registered strategies in code. The Phase 1A-beta cube is the lenient run with all four legacy gates OFF (cap / dd-halt / regime / event suppression - those return in Phase 1B-alpha only). In this run, ${rows.length} fired &gt;= 1 trade and made the table; the remaining ${(pza.quiet_count != null ? pza.quiet_count : "~85")} are quiet (see Tab 12 for the 3-bucket diagnosis: PRODUCER_LAYER_ZERO_LIKELY / COMPOUND_RESTRICTIVE / SKIPPED_AT_ENGINE).
    `;
  }
  // Columns — auto-detect
  const cols = Object.keys(rows[0]).map(k => ({
    title: k, data: k,
    render: (v) => {
      if (v === null || v === undefined) return "—";
      if (typeof v === "boolean") return v ? '<span class="pill pass">PASS</span>' : '<span class="pill fail">FAIL</span>';
      if (typeof v === "number") return Number.isInteger(v) ? v.toLocaleString() : v.toFixed(3);
      return String(v);
    },
  }));
  buildTable("#strategies-table", rows, { columns: cols, pageLength: 25 });
  $("#winning-pre").textContent = JSON.stringify(D.winning_strategies || {}, null, 2);
}

// ---- TAB: Regime ----
function renderRegime() {
  // Batch 433 (2026-05-29): data structure is
  //   { strategy: { regime_verdicts: { regime: "PASS"|"FAIL"|... },
  //                 overall_win_rate, total_trades, passes_all, best_regimes } }
  // Previous code read top-level strategy keys AS regimes - so the
  // columns became literally `best_regimes / regime_verdicts /
  // overall_win_rate / total_trades / passes_all`, none of which are
  // verdict strings, so every cell rendered empty.
  const matrix = D.strategy_regime_matrix || {};
  const strategies = Object.keys(matrix);
  const wrap = $("#regime-heatmap");
  if (!strategies.length) { wrap.innerHTML = '<div class="empty">No strategy_regime_matrix.json</div>'; return; }
  // Extract regime names from each strategy's regime_verdicts dict.
  const regimes = Array.from(new Set(
    strategies.flatMap(s => Object.keys((matrix[s] || {}).regime_verdicts || {}))
  ));
  // 3 trailing summary columns: total_trades, overall_win_rate, passes_all.
  const summaryCols = ["Trades", "Win %", "Passes"];
  const totalCols = 1 + regimes.length + summaryCols.length;
  let html = `<div class="heatmap" style="grid-template-columns: 250px repeat(${regimes.length}, minmax(80px, 1fr)) repeat(${summaryCols.length}, minmax(70px, 1fr))">`;
  html += `<div class="cell" style="background:#0d1117;color:var(--muted);font-weight:600">Strategy ↓ / Regime →</div>`;
  for (const r of regimes) html += `<div class="cell" style="background:#0d1117;color:var(--muted);font-weight:600">${r}</div>`;
  for (const c of summaryCols) html += `<div class="cell" style="background:#0d1117;color:var(--accent);font-weight:600">${c}</div>`;
  for (const s of strategies) {
    const entry = matrix[s] || {};
    const verdicts = entry.regime_verdicts || {};
    html += `<div class="cell" style="background:#0d1117;text-align:left;font-weight:500">${s}</div>`;
    for (const r of regimes) {
      const v = verdicts[r] || "";
      let bg = "#30363d", color = "var(--muted)";
      if (v === "PASS") { bg = "#10b98155"; color = "#10b981"; }
      else if (v === "FAIL") { bg = "#ef444455"; color = "#ef4444"; }
      else if (v === "INSUFFICIENT_DATA") { bg = "#f59e0b33"; color = "#f59e0b"; }
      html += `<div class="cell" style="background:${bg};color:${color}" title="${s} / ${r}: ${v}">${v || "—"}</div>`;
    }
    // Summary columns
    const trades = entry.total_trades;
    const winRate = entry.overall_win_rate;
    const passes = entry.passes_all;
    const passClass = passes === true ? "#10b98155" : passes === false ? "#ef444455" : "#30363d";
    const passColor = passes === true ? "#10b981" : passes === false ? "#ef4444" : "var(--muted)";
    html += `<div class="cell" style="background:#0d1117;color:var(--text)">${fmtInt(trades)}</div>`;
    html += `<div class="cell" style="background:#0d1117;color:var(--text)">${fmtPct(winRate, 1)}</div>`;
    html += `<div class="cell" style="background:${passClass};color:${passColor};font-weight:600">${passes === true ? "✓" : passes === false ? "✗" : "—"}</div>`;
  }
  html += "</div>";
  wrap.innerHTML = html;
  $("#regime-summary-pre").textContent = JSON.stringify(D.regime_stratified_summary || {}, null, 2);
}

// ---- TAB: MAE/MFE ----
function renderMaeMfe() {
  buildTable("#mae-table", D.mae_bucket || []);
  buildTable("#mfe-table", D.mfe_bucket || []);
}

// ---- TAB: Equity ----
function renderEquity() {
  const curve = D.equity_curve || [];
  const psum = D.portfolio_summary || {};
  const pmetrics = D.portfolio_metrics || {};
  $("#equity-kpis").innerHTML = [
    kpi(curve.length, "Days"),
    kpi(fmtPct(pmetrics.total_return ?? psum.portfolio_return_pct, 1), "Total return"),
    kpi(fmtNum(pmetrics.sharpe, 2), "Sharpe"),
    kpi(fmtPct(pmetrics.max_dd, 1), "Max DD"),
    kpi(fmtNum(pmetrics.alpha, 2), "Alpha vs SPY"),
    kpi(fmtNum(pmetrics.beta, 2), "Beta vs SPY"),
  ].join("");
  if (!curve.length) return;
  const labels = curve.map(p => p.date);
  const data = curve.map(p => Number(p.equity));
  new Chart(document.getElementById("equity-chart"), {
    type: "line",
    data: { labels, datasets: [{ label: "Portfolio equity", data, borderColor: "#58a6ff", backgroundColor: "rgba(88,166,255,0.1)", fill: true, tension: 0.1, pointRadius: 0 }] },
    options: {
      responsive: true,
      plugins: { legend: { labels: { color: "#c9d1d9" } } },
      scales: {
        x: { ticks: { color: "#8b949e", maxTicksLimit: 10 }, grid: { color: "#30363d" } },
        y: { ticks: { color: "#8b949e" }, grid: { color: "#30363d" } },
      },
    },
  });
}

// ---- TAB: Walk-forward ----
function renderWalkForward() {
  $("#improvements-pre").textContent = JSON.stringify(D.improvements_summary || {}, null, 2);
  $("#rolling-pre").textContent = JSON.stringify(D.rolling_sharpe_stability || {}, null, 2);
  $("#stress-pre").textContent = JSON.stringify(D.stress_metrics || {}, null, 2);
  buildTable("#bootstrap-table", D.bootstrap_ci || []);
}

// ---- TAB: Smart Money ----
function renderSmartMoney() {
  buildTable("#smartmoney-table", D.smart_money_exit || []);
  buildTable("#congressional-table", D.congressional_correlation || []);
}

// ---- TAB: Sector ----
function renderSector() {
  buildTable("#sector-table", D.by_sector || []);
  buildTable("#sector-conc-table", D.sector_concentration || []);
}

// ---- TAB: Skipped ----
function renderSkipped() {
  buildTable("#skipped-table", D.skipped_trades || [], { pageLength: 25 });
}

// ---- TAB: Circuit breakers ----
function renderCircuit() {
  buildTable("#cb-log-table", D.circuit_breaker_log || []);
  buildTable("#cb-active-table", D.cb_by_active || []);
}

// ---- TAB: Exits ----
function renderExits() {
  buildTable("#exit-best-table", D.exit_best || []);
  buildTable("#exit-comparison-table", D.exit_comparison || []);
  buildTable("#exit-cube-table", (D.exit_methods || []).slice(0, 200));
  // Per-dimension breakdowns
  const breakdowns = D.exit_breakdowns || {};
  const wrap = $("#exit-breakdowns");
  wrap.innerHTML = "";
  for (const [name, rows] of Object.entries(breakdowns)) {
    if (!rows || !rows.length) continue;
    const id = `bd-${name.replace(/[^a-z0-9]/gi, "_")}`;
    const det = document.createElement("details");
    det.innerHTML = `<summary>${name} (${rows.length} rows)</summary><table id="${id}" class="display compact"></table>`;
    wrap.appendChild(det);
    setTimeout(() => buildTable("#" + id, rows, { pageLength: 10 }), 0);
  }
}

// ---- TAB: Trades ----
function renderTrades() {
  const rows = D.trade_log_preview || [];
  buildTable("#trades-table", rows, { pageLength: 25 });
}

// ---- TAB: Raw ----
function renderRaw() {
  const summary = {};
  for (const [k, v] of Object.entries(D)) {
    if (Array.isArray(v)) summary[k] = `array[${v.length}]`;
    else if (v && typeof v === "object") summary[k] = `object{${Object.keys(v).length}}`;
    else summary[k] = String(v).slice(0, 80);
  }
  $("#raw-pre").textContent = JSON.stringify(summary, null, 2);
}

// ---- Batch 419 renderers: cube-optimizer tabs (per locked workflow Stage 3) ----
function renderOptimizer() {
  const md = D.optimizer_summary_md || "";
  const psc = D.per_strategy_candidates || {};
  const ema = D.exit_method_analysis || {};
  const pza = D.producer_zero_audit || {};
  const optDir = D.optimizer_dir || "(none)";
  const summary = pza.summary || {};
  const passCells = ((ema.proposals || []).find(p => p.includes("PASS DEC-426")) || "(no PASS proposals)").slice(0, 200);
  const top5Em = ema.proposals && ema.proposals[0] || "(no L1 ranking)";
  const html = [
    kpi(Object.keys(psc).length, "Strategies analyzed"),
    kpi(summary.fired_count ?? "—", "Fired"),
    kpi(summary.quiet_count ?? "—", "Quiet"),
    kpi(summary.COMPOUND_RESTRICTIVE ?? "—", "Compound restrictive"),
  ].join("");
  $("#optimizer-kpis").innerHTML = html;
  // Batch 430 (2026-05-29): render markdown via marked.js for readability.
  // Was: raw markdown text dumped into <pre> with .textContent.
  const target = $("#optimizer-md-rendered");
  if (md) {
    if (typeof marked !== "undefined" && marked && marked.parse) {
      target.innerHTML = marked.parse(md.slice(0, 50000));
    } else {
      // marked.js failed to load -> fall back to escaped raw text
      target.style.whiteSpace = "pre-wrap";
      target.textContent = md.slice(0, 50000);
    }
  } else {
    target.textContent = `(no optimization_summary.md found at ${optDir})`;
  }
}

function renderCandidates() {
  const psc = D.per_strategy_candidates || {};
  const picker = $("#candidate-picker");
  const detail = $("#candidate-detail");
  const names = Object.keys(psc).sort();
  if (!names.length) {
    detail.textContent = "(no per-strategy JSONs found)";
    return;
  }
  picker.innerHTML = names.map(n => `<option value="${n}">${n}</option>`).join("");
  function show(name) {
    // Batch 430: structured render (was: raw JSON.stringify dump).
    const obj = psc[name] || {};
    const agg = obj.aggregate || {};
    const dims = [
      ["A — Thresholds",      obj.dimension_a_thresholds],
      ["B — Compound logic",  obj.dimension_b_compound],
      ["C — Regime",          obj.dimension_c_regime],
      ["D — Exit method",     obj.dimension_d_exit],
      ["E — Sizing",          obj.dimension_e_sizing],
      ["F — Universe",        obj.dimension_f_universe],
      ["G — Hold",            obj.dimension_g_hold],
      ["H — Cooldown",        obj.dimension_h_cooldown],
      ["I — Macro",           obj.dimension_i_macro],
    ];
    const verdictClass = agg.verdict === "PASS" ? "good"
      : agg.verdict === "FAIL" ? "bad" : "warn";
    const aggKpis = [
      kpi(fmtInt(agg.n), "Trades (n)"),
      kpi(fmtPct(agg.win_rate, 1), "Win rate"),
      kpi(fmtNum(agg.sharpe, 2), "Sharpe", (agg.sharpe ?? 0) >= 0.7 ? "good" : "bad"),
      kpi(fmtNum(agg.profit_factor, 2), "PF", (agg.profit_factor ?? 0) >= 1.3 ? "good" : "bad"),
      kpi(fmtNum(agg.t_stat, 2), "t-stat", (agg.t_stat ?? 0) >= 3.4 ? "good" : "warn"),
      kpi(agg.verdict || "—", "Verdict", verdictClass),
      kpi(agg.five_gate_pass ? "✓" : "✗", "5-Gate strict", agg.five_gate_pass ? "good" : "bad"),
    ].join("");
    const dimRows = dims.map(([label, dim]) => {
      if (!dim) return `<tr><td>${label}</td><td>—</td><td>—</td><td>—</td></tr>`;
      const status = dim.status || "—";
      const cands = Array.isArray(dim.candidates) ? dim.candidates.length
        : (dim.proposals && dim.proposals.length) ? dim.proposals.length : 0;
      const notes = (dim.proposals && dim.proposals[0]) ? dim.proposals[0]
        : (dim.restrictive && dim.restrictive.length) ? `${dim.restrictive.length} restrictive`
        : (dim.candidates && dim.candidates[0]) ? `top: ${JSON.stringify(dim.candidates[0]).slice(0,80)}…`
        : "—";
      return `<tr><td>${label}</td><td>${status}</td><td>${cands}</td><td style="font-size:.75rem;color:var(--muted)">${notes}</td></tr>`;
    }).join("");
    detail.innerHTML = `
      <div class="kpis" style="margin-bottom:.75rem">${aggKpis}</div>
      <h4 style="margin:.5rem 0">Per-dimension summary (${obj.n_trades ?? 0} trades total)</h4>
      <table class="display compact" style="width:100%;font-size:.8rem">
        <thead><tr><th>Dimension</th><th>Status</th><th>Candidates / Proposals</th><th>Top note</th></tr></thead>
        <tbody>${dimRows}</tbody>
      </table>
      <details style="margin-top:.75rem">
        <summary style="cursor:pointer;color:var(--muted);font-size:.8rem">Raw JSON (full payload)</summary>
        <pre style="font-size:.7rem;color:var(--muted);background:#0d1117;padding:.5rem;border-radius:4px;overflow:auto;max-height:400px;white-space:pre-wrap">${JSON.stringify(obj, null, 2)}</pre>
      </details>
    `;
  }
  picker.addEventListener("change", () => show(picker.value));
  show(names[0]);
}

function renderQuiet() {
  const pza = D.producer_zero_audit || {};
  const buckets = pza.buckets || {};
  const sum = pza.summary || {};
  $("#quiet-kpis").innerHTML = [
    kpi(sum.PRODUCER_LAYER_ZERO_LIKELY ?? "—", "PLZ_LIKELY"),
    kpi(sum.COMPOUND_RESTRICTIVE ?? "—", "Compound restrictive"),
    kpi(sum.SKIPPED_AT_ENGINE ?? "—", "Skipped at engine"),
    kpi(sum.quiet_count ?? "—", "Total quiet"),
  ].join("");
  $("#quiet-plz").innerHTML = (buckets.PRODUCER_LAYER_ZERO_LIKELY || [])
    .map(s => `<li>${s}</li>`).join("") || "<li><em>(empty)</em></li>";
  $("#quiet-cr").innerHTML = (buckets.COMPOUND_RESTRICTIVE || [])
    .map(s => `<li>${s}</li>`).join("") || "<li><em>(empty)</em></li>";
  $("#quiet-skip").innerHTML = (buckets.SKIPPED_AT_ENGINE || [])
    .map(s => `<li>${s}</li>`).join("") || "<li><em>(empty)</em></li>";
}

function renderCubeCells() {
  const ema = D.exit_method_analysis || {};
  const l2 = (ema.layer_2_per_strategy_exit_cell || []).map(r => ({
    strategy:        r.strategy,
    exit_method:     r.exit_method,
    n:               r.n,
    sharpe:          fmtNum(r.sharpe, 3),
    win_rate:        fmtNum(r.win_rate, 3),
    profit_factor:   fmtNum(r.profit_factor, 2),
    t_stat:          fmtNum(r.t_stat, 2),
    bonferroni_p:    fmtNum(r.bonferroni_p, 4),
    verdict:         r.verdict || "—",
    five_gate_pass:  r.five_gate_pass ? "✓" : "✗",
  }));
  buildTable("#cube-cells-table", l2, {
    pageLength: 25,
    order: [[3, "desc"]],  // sort by Sharpe DESC
  });
}

// ---- Batch 443 (2026-05-29): global round banner + Tab 17 + Tab 18 ----
function renderRoundBanner() {
  const banner = document.getElementById("round-banner");
  if (!banner) return;
  const cur = D.current_round;
  const rounds = D.iteration_rounds || [];
  const meta = rounds.find(r => r.id === cur) || (rounds[rounds.length - 1]) || {};
  if (!cur) {
    banner.innerHTML = `<strong>No round metadata found.</strong> Populate <code>archive/cube_rounds/rounds.json</code> and rebuild.`;
    return;
  }
  const trades = (meta.trades_total || "?").toLocaleString();
  banner.innerHTML = `<strong>Showing data from ${cur}</strong> (${meta.label || ""}) - completed ${meta.date_completed || "?"} - commit <code>${(meta.commit || "?").slice(0, 24)}</code> - ${trades} trades / ${meta.n_strategies_fired || "?"} fired strategies / ${meta.L2_cells_n_gte_5 || "?"} L2 cells. See Tab 17 for full round history; Tab 18 for per-cell cross-round comparison.`;
}

function renderRounds() {
  const rounds = D.iteration_rounds || [];
  if (!rounds.length) {
    const t = document.getElementById("rounds-detail");
    if (t) t.innerHTML = '<div class="empty">No iteration rounds registered.</div>';
    return;
  }
  // Summary table: one row per round.
  const rows = rounds.map(r => ({
    id:              r.id,
    label:           r.label,
    date:            r.date_completed,
    commit:          (r.commit || "").slice(0, 24),
    universe:        r.universe_size_traded,
    window:          `${r.time_window_start} -> ${r.time_window_end}`,
    strategies:      `${r.n_strategies_fired}/${r.n_strategies_registered} fired`,
    quiet:           r.n_strategies_quiet,
    PRODUCER:        (r.buckets || {}).PRODUCER_LAYER_ZERO_LIKELY,
    COMPOUND:        (r.buckets || {}).COMPOUND_RESTRICTIVE,
    SKIPPED:         (r.buckets || {}).SKIPPED_AT_ENGINE,
    L2_cells:        r.L2_cells_n_gte_5,
    trades:          r.trades_total,
  }));
  buildTable("#rounds-summary-table", rows, { pageLength: 10 });
  // Per-round detail blocks (collapsible, latest first).
  const target = $("#rounds-detail");
  if (target) {
    const blocks = [...rounds].reverse().map((r, i) => {
      const objList = (r.objectives || []).map(o => `<li>${o}</li>`).join("");
      const chgList = (r.changes_from_prior || []).map(o => `<li>${o}</li>`).join("");
      const finList = (r.findings || []).map(o => `<li>${o}</li>`).join("");
      const open = i === 0 ? "open" : "";
      return `
        <details ${open} style="margin:.4rem 0;background:#1a1f29;border:1px solid var(--border);padding:.5rem .8rem;border-radius:6px">
          <summary style="cursor:pointer;color:var(--accent);font-weight:600">${r.id} - ${r.label} (${r.date_completed})</summary>
          <div style="font-size:.85rem;margin-top:.5rem">
            <p style="margin:.2rem 0"><strong>Infra:</strong> ${r.infra || "—"}</p>
            <p style="margin:.2rem 0"><strong>Universe traded:</strong> ${r.universe_size_traded} unique tickers / window ${r.time_window_start} to ${r.time_window_end}</p>
            <p style="margin:.2rem 0"><strong>Commit:</strong> <code>${r.commit}</code></p>
            <p style="margin:.4rem 0 .2rem"><strong>Objectives:</strong></p><ul style="margin:.2rem 0;padding-left:1.4rem">${objList}</ul>
            <p style="margin:.4rem 0 .2rem"><strong>Changes from prior round:</strong></p><ul style="margin:.2rem 0;padding-left:1.4rem">${chgList}</ul>
            <p style="margin:.4rem 0 .2rem"><strong>Findings:</strong></p><ul style="margin:.2rem 0;padding-left:1.4rem">${finList}</ul>
          </div>
        </details>
      `;
    }).join("");
    target.innerHTML = blocks;
  }
}

function renderCellCompare() {
  const rows = D.cell_cube_comparison || [];
  const ids = D.round_ids || [];
  if (!rows.length || !ids.length) return;
  // KPIs.
  const moved = rows.filter(r => r.sharpe_delta_R3_R2 != null && Math.abs(r.sharpe_delta_R3_R2) > 0.01).length;
  const up = rows.filter(r => (r.sharpe_delta_R3_R2 || 0) > 0).length;
  const down = rows.filter(r => (r.sharpe_delta_R3_R2 || 0) < 0).length;
  const onlyCurrent = rows.filter(r => r[`${ids[ids.length-1]}_n`] != null && r[`${ids[0]}_n`] == null).length;
  const onlyPrior = rows.filter(r => r[`${ids[0]}_n`] != null && r[`${ids[ids.length-1]}_n`] == null).length;
  const kpis = $("#cellcompare-kpis");
  if (kpis) {
    kpis.innerHTML = [
      kpi(rows.length, "Total cells (union)"),
      kpi(moved, "Cells with |delta| > 0.01"),
      kpi(up, "Improved", "good"),
      kpi(down, "Regressed", "bad"),
      kpi(onlyCurrent, "New in latest", "good"),
      kpi(onlyPrior, "Retired in latest", "warn"),
    ].join("");
  }
  // Build per-round columns dynamically.
  const cols = [
    { title: "Strategy", data: "strategy" },
    { title: "Exit method", data: "exit_method" },
  ];
  for (const rid of ids) {
    cols.push({ title: `${rid} n`, data: `${rid}_n`, render: v => v == null ? "—" : v });
    cols.push({ title: `${rid} Sharpe`, data: `${rid}_sharpe`, render: v => v == null ? "—" : Number(v).toFixed(2) });
    cols.push({ title: `${rid} verdict`, data: `${rid}_verdict`, render: v => v || "—" });
  }
  if (ids.length >= 2) {
    cols.push({ title: `${ids[ids.length-1]}-${ids[0]} ΔSharpe`,
                data: "sharpe_delta_R3_R2",
                render: v => v == null ? "—" : (v > 0 ? "+" : "") + Number(v).toFixed(2) });
  }
  buildTable("#cellcompare-table", rows, {
    columns: cols,
    pageLength: 25,
    order: [[cols.length - 1, "desc"]],
  });
}

// ---- Batch 441 (2026-05-29): Cube Diff iteration tracking tab ----
function renderCubeDiff() {
  const diff = D.cube_diff;
  if (!diff || Object.keys(diff).length === 0) {
    // No diff payload yet (pre-merge or build script not yet extended).
    // The static <details> block in index.html already explains the
    // run objectives + the "TBD" trade-count entries; the live-diff
    // section shows its own "Diff not yet computed" callout. Nothing
    // to render here until D.cube_diff appears.
    return;
  }
  // KPIs.
  const kpis = $("#cubediff-kpis");
  if (kpis) {
    kpis.innerHTML = [
      kpi(diff.total_trades_prior || "—", "Trades (prior)"),
      kpi(diff.total_trades_current || "—", "Trades (current)"),
      kpi((diff.cells_improved || 0), "Cells improved", "good"),
      kpi((diff.cells_regressed || 0), "Cells regressed", "bad"),
      kpi((diff.cells_new || 0), "New cells", "good"),
      kpi((diff.cells_retired || 0), "Retired cells", "warn"),
      kpi((diff.verdict_upgrades || 0), "Verdict upgrades", "good"),
      kpi((diff.verdict_downgrades || 0), "Verdict downgrades", "bad"),
    ].join("");
  }
  // Hide the "not yet computed" callout when diff IS computed.
  const status = $("#cubediff-status");
  if (status) status.style.display = "none";
  // Buckets table.
  if (diff.bucket_diff) {
    const rows = Object.entries(diff.bucket_diff).map(([b, d]) => ({
      bucket: b, prior: d.prior, current: d.current, delta: d.delta,
    }));
    buildTable("#cubediff-buckets", rows, { pageLength: 10 });
  }
  // Improved + regressed cells.
  if (Array.isArray(diff.cells_improved_top20)) {
    buildTable("#cubediff-improved", diff.cells_improved_top20, { pageLength: 20 });
  }
  if (Array.isArray(diff.cells_regressed_top20)) {
    buildTable("#cubediff-regressed", diff.cells_regressed_top20, { pageLength: 20 });
  }
}

// ---- Batch 434 (2026-05-29): Reference / Background tab ----
function renderReference() {
  // Populate top-of-tab live counts. Static content is in index.html;
  // these KPIs come from the live data so the numbers reflect the
  // current run rather than a stale doc.
  const pza = (D.producer_zero_audit || {}).summary || {};
  const psc = D.per_strategy_candidates || {};
  const rows = D.backtest_results || [];
  const ema = D.exit_method_analysis || {};
  const l2 = (ema.layer_2_per_strategy_exit_cell || []);
  const distinctExits = new Set(l2.map(r => r.exit_method).filter(Boolean));
  const target = $("#reference-counts");
  if (!target) return;
  target.innerHTML = [
    kpi(pza.active_count != null ? pza.active_count : 185, "Strategies registered"),
    kpi(pza.fired_count != null ? pza.fired_count : "—", "Fired ≥1 trade", pza.fired_count > 0 ? "good" : "warn"),
    kpi(rows.length, "In Tab 1 (CSV-included)"),
    kpi(pza.quiet_count != null ? pza.quiet_count : "—", "Quiet (Tab 12)", "warn"),
    kpi(Object.keys(psc).length || 101, "Per-strategy JSONs"),
    kpi(distinctExits.size || 25, "Exit methods"),
    kpi(9, "Success criteria"),
    kpi(7, "Historical regime windows"),
  ].join("");
}

// ---- Render all ----
try { renderOverview(); } catch (e) { console.error("overview:", e); }
try { renderStrategies(); } catch (e) { console.error("strategies:", e); }
try { renderRegime(); } catch (e) { console.error("regime:", e); }
try { renderMaeMfe(); } catch (e) { console.error("maemfe:", e); }
try { renderEquity(); } catch (e) { console.error("equity:", e); }
try { renderWalkForward(); } catch (e) { console.error("walkforward:", e); }
try { renderSmartMoney(); } catch (e) { console.error("smartmoney:", e); }
try { renderSector(); } catch (e) { console.error("sector:", e); }
try { renderSkipped(); } catch (e) { console.error("skipped:", e); }
try { renderCircuit(); } catch (e) { console.error("circuit:", e); }
try { renderExits(); } catch (e) { console.error("exits:", e); }
try { renderTrades(); } catch (e) { console.error("trades:", e); }
// Batch 419 tabs
try { renderOptimizer(); } catch (e) { console.error("optimizer:", e); }
try { renderCandidates(); } catch (e) { console.error("candidates:", e); }
try { renderQuiet(); } catch (e) { console.error("quiet:", e); }
try { renderCubeCells(); } catch (e) { console.error("cubecells:", e); }
// Batch 434: Reference / Background tab
try { renderReference(); } catch (e) { console.error("reference:", e); }
// Batch 441: Cube Diff iteration tracking tab
try { renderCubeDiff(); } catch (e) { console.error("cubediff:", e); }
// Batch 443: global round banner + Iteration Rounds + Cell Cube Comparison
try { renderRoundBanner(); } catch (e) { console.error("roundbanner:", e); }
try { renderRounds(); } catch (e) { console.error("rounds:", e); }
try { renderCellCompare(); } catch (e) { console.error("cellcompare:", e); }
try { renderRaw(); } catch (e) { console.error("raw:", e); }
