// Stage 3 dashboard data. Auto-generated by build_dashboard_stage_3.py.
window.STAGE3_DATA = {
  "last_update": "2026-05-20 03:57 UTC",
  "portfolio": {
    "starting_value": 100000.0,
    "current_value": 100000.0,
    "cash": 100000.0,
    "n_open": 0,
    "daily_pnl_dollar": 0,
    "current_dd_pct": 0,
    "peak_value": 100000.0,
    "open_positions": []
  },
  "closed_trades": [],
  "todays_picks": [],
  "journal_entries": []
};
