"""Build Stage 3 dashboard data.js from paper portfolio state (Batch 257).

Source: per CHECKLIST #77 - paper portfolio state at output_paper/portfolio.json
(written by backtest.paper_trading.paper_portfolio.PaperPortfolio.save).
Picks source: output_paper/picks_*.parquet (written by run_paper_morning.py).
Journal source: dashboard_stage_3/journal/*.md (written by run_paper_end_of_day.py).

Refreshes /dashboard_stage_3/data.js with current paper portfolio state
+ today's picks + recent journal entries.

Usage:
  python scripts/build_dashboard_stage_3.py
  python scripts/build_dashboard_stage_3.py --portfolio output_paper/portfolio.json
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]


def main() -> int:
    p = argparse.ArgumentParser(description="Build Stage 3 dashboard data")
    p.add_argument("--portfolio", default="output_paper/portfolio.json")
    p.add_argument("--picks-dir", default="output_paper")
    p.add_argument("--journal-dir", default="dashboard_stage_3/journal")
    p.add_argument("--output", default="dashboard_stage_3/data.js")
    args = p.parse_args()

    out_path = REPO / args.output

    # Load portfolio state
    portfolio_path = REPO / args.portfolio
    portfolio = {
        "starting_value":   100000.00,
        "current_value":    100000.00,
        "cash":             100000.00,
        "n_open":           0,
        "daily_pnl_dollar": 0,
        "current_dd_pct":   0,
        "peak_value":       100000.00,
        "open_positions":   [],
    }
    closed_trades = []
    if portfolio_path.exists():
        try:
            pdata = json.loads(portfolio_path.read_text())
            portfolio.update({
                "starting_value":   pdata.get("starting_value", 100000),
                "current_value":    pdata.get("current_value", 100000),
                "cash":             pdata.get("cash", 100000),
                "n_open":           len(pdata.get("open_positions", [])),
                "daily_pnl_dollar": 0,  # computed at EOD only
                "current_dd_pct":   pdata.get("current_dd_pct", 0),
                "peak_value":       pdata.get("peak_value", 100000),
                "open_positions":   pdata.get("open_positions", []),
            })
            closed_trades = pdata.get("closed_trades", [])
        except Exception as exc:
            print(f"[WARN] portfolio.json read failed: {exc}")

    # Load today's picks
    todays_picks = []
    picks_dir = REPO / args.picks_dir
    if picks_dir.exists():
        latest_picks = sorted(picks_dir.glob("picks_*.parquet"))
        if latest_picks:
            try:
                import pandas as pd
                df = pd.read_parquet(latest_picks[-1])
                todays_picks = df.to_dict(orient="records")
            except Exception as exc:
                print(f"[WARN] picks read failed: {exc}")

    # Load journal entries
    journal_entries = []
    journal_dir = REPO / args.journal_dir
    if journal_dir.exists():
        # Last 10 days only
        for jpath in sorted(journal_dir.glob("*.md"))[-10:]:
            journal_entries.append({
                "date":     jpath.stem,
                "markdown": jpath.read_text(encoding="utf-8"),
            })

    data = {
        "last_update":     datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "portfolio":       portfolio,
        "closed_trades":   closed_trades,
        "todays_picks":    todays_picks,
        "journal_entries": journal_entries,
    }

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        "// Stage 3 dashboard data. Auto-generated by build_dashboard_stage_3.py.\n"
        + "window.STAGE3_DATA = "
        + json.dumps(data, indent=2, default=str)
        + ";\n",
        encoding="utf-8",
    )
    print(f"[OK] wrote {out_path.relative_to(REPO)}: "
          f"{portfolio['n_open']} open, {len(closed_trades)} closed, "
          f"{len(todays_picks)} picks, {len(journal_entries)} journal entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
