#!/usr/bin/env python
"""S6-B2580a: per-section provenance for STRATEGY_OPTIMISATION_PLAN.md.

THE PROBLEM. The plan is ~3,983 lines across 159 sections and carries no
per-section provenance, so a reader cannot tell a CURRENT rule from a
SUPERSEDED one without git archaeology. 43 of the 159 headers name a batch
inline; the other 116 do not.

WHY THIS IS A GENERATOR AND NOT A HAND-WRITTEN APPENDIX. The ticket deferred
this as "a mechanical pass best done in one turn against git log -p --follow".
A hand-written appendix is stale the next time anyone edits the plan - which
is the exact failure the plan already has, reproduced in the fix (#281: a
generated artifact older than its generator is stale, full stop). Regenerating
costs one blame pass, so the appendix stays true by being rebuilt rather than
by being remembered.

METHOD. One `git blame --line-porcelain` over the file, then per section take
the MOST RECENT commit touching any line in its range. That answers "when was
this section last amended", which is the question a reader asking "is this
current?" actually has. It does NOT claim to identify the batch that AUTHORED
a section - a later typo fix would mask it - and the appendix says so rather
than implying an authorship it cannot support.

    python scripts/plan_lineage.py            # print the appendix
    python scripts/plan_lineage.py --write    # write it into the plan
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLAN = ROOT / "STRATEGY_OPTIMISATION_PLAN.md"
MARK_START = "<!-- LINEAGE-APPENDIX:START (generated by scripts/plan_lineage.py) -->"
MARK_END = "<!-- LINEAGE-APPENDIX:END -->"


def blame_lines(path: Path):
    """line number -> (short sha, author-date, subject-batch) via ONE blame."""
    out = subprocess.run(
        ["git", "blame", "--line-porcelain", "--", path.name],
        cwd=str(path.parent), capture_output=True, text=True,
        errors="replace", timeout=300)
    if out.returncode != 0:
        return {}
    info, cur, lineno = {}, {}, 0
    for ln in out.stdout.splitlines():
        m = re.match(r"^([0-9a-f]{40}) \d+ (\d+)", ln)
        if m:
            cur = {"sha": m.group(1)[:9]}
            lineno = int(m.group(2))
        elif ln.startswith("author-time "):
            cur["t"] = int(ln.split()[1])
        elif ln.startswith("summary "):
            cur["subject"] = ln[len("summary "):]
            info[lineno] = dict(cur)
    return info


def sections(text: str):
    """(level, title, start_line, end_line) for every ## / ### header."""
    lines = text.splitlines()
    heads = [(i + 1, ln) for i, ln in enumerate(lines)
             if re.match(r"^#{2,3} ", ln)]
    out = []
    for idx, (n, ln) in enumerate(heads):
        end = heads[idx + 1][0] - 1 if idx + 1 < len(heads) else len(lines)
        lvl = len(ln) - len(ln.lstrip("#"))
        out.append((lvl, ln.lstrip("# ").strip(), n, end))
    return out


def _strip_appendix(text: str) -> str:
    """Blank out a previously-generated appendix, PRESERVING line
    numbers so blame offsets still line up.

    B2935: without this the appendix's own `## APPENDIX L` header is
    parsed as a plan section on the next run, so the table grows by a
    row about the generator every regeneration. MEASURED: 156
    insertions on the first write, 157 on the second.

    Blanking in place rather than deleting is deliberate - L582: a
    strip that REBUILDS its haystack shifts every offset after it, and
    here the offsets are what join a section to its blame."""
    if MARK_START not in text or MARK_END not in text:
        return text
    i = text.index(MARK_START)
    j = text.index(MARK_END) + len(MARK_END)
    inner = text[i:j]
    return text[:i] + ("\n" * inner.count("\n")) + text[j:]


def build_appendix() -> str:
    text = _strip_appendix(
        PLAN.read_text(encoding="utf-8", errors="replace"))
    info = blame_lines(PLAN)
    if not info:
        return ("\n> LINEAGE APPENDIX UNAVAILABLE - `git blame` returned "
                "nothing. Not a claim that the plan has no history; the "
                "generator could not read it (S6-B2580a).\n")

    rows = []
    for lvl, title, a, b in sections(text):
        best = None
        for n in range(a, b + 1):
            d = info.get(n)
            if d and (best is None or d.get("t", 0) > best.get("t", 0)):
                best = d
        if not best:
            continue
        import datetime as _dt
        when = _dt.datetime.fromtimestamp(
            best["t"], _dt.timezone.utc).strftime("%Y-%m-%d")
        subj = (best.get("subject") or "")
        bm = re.match(r"^(B\d{3,4}[a-z]?)", subj)
        rows.append((lvl, title, when, best["sha"], bm.group(1) if bm else "-",
                     subj[:58]))

    rows.sort(key=lambda r: r[2], reverse=True)
    out = [MARK_START, "",
           "## APPENDIX L - PER-SECTION LINEAGE (generated; do not hand-edit)",
           "",
           "**S6-B2580a.** This plan carries rules written across hundreds of "
           "batches, and without per-section provenance a reader cannot tell "
           "a CURRENT rule from a SUPERSEDED one without git archaeology. "
           "Regenerate with `python scripts/plan_lineage.py --write`.",
           "",
           "**WHAT THIS COLUMN MEANS, stated rather than implied:** *last "
           "amended* is the most recent commit touching ANY line in the "
           "section, taken from one `git blame` pass. It answers *is this "
           "section current?*. It does NOT identify the batch that AUTHORED "
           "the section - a later typo fix masks the author - so do not read "
           "it as authorship. Sections are listed most-recently-amended "
           "first, so the STALEST rules are at the bottom, which is where a "
           "reader checking for superseded text should start.",
           "",
           f"**{len(rows)} sections.** Generated from the working tree; a row "
           "is only as current as the last regeneration (#281).",
           "",
           "| section | last amended | batch | commit |",
           "|---|---|---|---|"]
    for lvl, title, when, sha, batch, subj in rows:
        ind = "" if lvl == 2 else "&nbsp;&nbsp;"
        t = title.replace("|", "/")[:88]
        out.append(f"| {ind}{t} | {when} | {batch} | `{sha}` |")
    out += ["", MARK_END]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true",
                    help="write the appendix into the plan (idempotent)")
    a = ap.parse_args()

    appendix = build_appendix()
    if not a.write:
        # L508: section titles carry emoji and this prints to a cp1252
        # console on Windows, where one of them takes the whole run down.
        # The ARTIFACT stays UTF-8 and intact - only stdout is narrow, so
        # only stdout is sanitized.
        sys.stdout.write(
            appendix.encode("ascii", "replace").decode("ascii") + "\n")
        return 0

    text = PLAN.read_text(encoding="utf-8", errors="replace")
    # S6-B3024: the DOMINANT ending, not ANY occurrence. Inferring from a
    # single match means one foreign line converts the whole appendix -
    # which is exactly how one CRLF row from the landing hook turned 119
    # later appends to EXECUTION_QUEUE.md into a 120-line flip. This plan
    # is stored pure LF today (4,141 bare LF, 0 CRLF at HEAD), so the old
    # expression is CORRECT here and latently wrong; majority makes it
    # robust rather than lucky.
    _crlf = text.count("\r\n")
    nl = "\r\n" if _crlf * 2 > text.count("\n") else "\n"
    body = appendix.replace("\n", nl)
    if MARK_START in text and MARK_END in text:
        i = text.index(MARK_START)
        j = text.index(MARK_END) + len(MARK_END)
        text = text[:i] + body + text[j:]
    else:
        text = text.rstrip() + nl + nl + body + nl
    # bytes, not write_text: on Windows this file is CRLF and re-encoding
    # every ending would stage thousands of phantom lines (L756 / C13)
    import io
    io.open(PLAN, "w", encoding="utf-8", newline="").write(text)
    print(f"wrote the lineage appendix into {PLAN.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
