"""Batch 625 (2026-06-08) -- walk pre-flight helper per CHECKLIST #105 (k).

Programmatic helper that Stage 4 walks invoke to produce a markdown-
ready pre-flight block. The block includes the mandatory fire-count
projection per CHECKLIST (k) so walks no longer have to re-derive
the format each time.

USAGE (from walk surface):

  from scripts.walk_preflight import walk_preflight_block
  print(walk_preflight_block(
      strategy="strat_my_new_strategy_long",
      proposed_gates=["resistance_break_retest", "obv_bullish",
                      "close_above_open", "vol_below_avg"],
      pre_walk_gate_count=2,           # gate count before the walk
      prior_deletion=None,             # or "B320 dropped vol_spike_2x"
  ))

The output is a markdown block that the walk can paste directly into
its surface message. The block contains:
  - Fire-count projection (independence-product upper bound)
  - Verdict (PASS_CUBE / WARN / FAIL / INCOMPLETE_PRIORS)
  - Gate-count delta vs pre-walk + reconciliation against prior
    deletion (if any)
  - Caveat about independence assumption

The COMMIT MESSAGE INVARIANT (enforced by
test_batch625_walk_commit_fire_count_pin.py): every walk commit
message must contain a `Fire-count projection:` line generated by
this helper (or an explicit `Fire-count projection: N/A - <reason>`
opt-out for non-walk batches).
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

# Make scripts/ importable
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.estimate_fire_count import estimate


# Sentinel string the pyramid test greps for. Keep this stable so
# commit-message scans + helper output stay coupled.
FIRE_COUNT_TOKEN = "Fire-count projection:"


def walk_preflight_block(
    strategy: str,
    proposed_gates: list[str],
    pre_walk_gate_count: Optional[int] = None,
    prior_deletion: Optional[str] = None,
    tickers: int = 220,
    trading_days: int = 252,
) -> str:
    """Build a markdown pre-flight block for a walk's surface message.

    Args:
      strategy: name of the strategy being walked
      proposed_gates: list of gate signal names AFTER the proposed walk
        changes (i.e., the post-walk gate set)
      pre_walk_gate_count: gate count BEFORE the walk (for delta
        reconciliation per CHECKLIST k)
      prior_deletion: human-readable note about any prior batch that
        DELETED a gate from this strategy (e.g., "B320 dropped
        vol_spike_2x for fire-count reason"). None if no prior
        deletion found.
      tickers: universe size for the projection (default 220)
      trading_days: trading days/year (default 252)
    """
    result = estimate(
        gates=proposed_gates,
        tickers=tickers,
        trading_days=trading_days,
    )
    fires_yr = result["fires_per_year_upper_bound"]
    verdict = result["verdict"]
    missing = result["missing_priors"]

    lines = []
    lines.append(f"**Pre-flight per CHECKLIST #105 (k) - {strategy}**")
    lines.append("")
    lines.append(
        f"{FIRE_COUNT_TOKEN} {fires_yr if fires_yr is not None else 'N/A'} "
        f"fires/yr UB (verdict: {verdict})"
    )
    lines.append(f"- Universe: {tickers} tickers x {trading_days} trading days")
    lines.append(f"- Post-walk gate count: {len(proposed_gates)}")
    if pre_walk_gate_count is not None:
        delta = len(proposed_gates) - pre_walk_gate_count
        sign = "+" if delta > 0 else ""
        lines.append(f"- Net change vs pre-walk: {sign}{delta} (pre-walk had {pre_walk_gate_count})")
    if prior_deletion:
        lines.append(f"- Prior deletion reconcile: {prior_deletion}")
    if missing:
        lines.append(
            f"- Missing priors: {', '.join(missing)} "
            f"(verdict is partial; expand PRIOR_RATES + re-run)"
        )
    if verdict in ("FAIL_FIRE_STARVED", "WARN_FIRE_STARVED"):
        lines.append(
            f"- **{verdict}**: per `feedback_minimum_fire_count_gate_before_cube`, "
            f"resolve by (1) drop a gate, (2) mark exploratory, or "
            f"(3) split into separate strategies before cube routing."
        )
    lines.append(
        "- Caveat: this is an INDEPENDENCE-PRODUCT upper bound; "
        "correlated gates produce LOWER actual fire rates."
    )
    return "\n".join(lines)


def walk_preflight_one_line(
    strategy: str,
    proposed_gates: list[str],
    tickers: int = 220,
    trading_days: int = 252,
) -> str:
    """Minimal one-line variant suitable for inclusion in commit
    messages. Contains the FIRE_COUNT_TOKEN so the pyramid scan
    recognises it.

    Format: `Fire-count projection: <N> fires/yr UB (verdict: <V>); gates: <K>`
    """
    result = estimate(
        gates=proposed_gates,
        tickers=tickers,
        trading_days=trading_days,
    )
    fires_yr = result["fires_per_year_upper_bound"]
    verdict = result["verdict"]
    return (
        f"{FIRE_COUNT_TOKEN} {fires_yr if fires_yr is not None else 'N/A'} "
        f"fires/yr UB (verdict: {verdict}); gates: {len(proposed_gates)}"
    )


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--strategy", required=True)
    parser.add_argument("--gates", nargs="+", required=True)
    parser.add_argument("--pre-walk-gates", type=int, default=None)
    parser.add_argument("--prior-deletion", default=None)
    parser.add_argument("--one-line", action="store_true",
                        help="One-line output for commit messages")
    args = parser.parse_args()
    if args.one_line:
        print(walk_preflight_one_line(args.strategy, args.gates))
    else:
        print(walk_preflight_block(
            args.strategy, args.gates,
            pre_walk_gate_count=args.pre_walk_gates,
            prior_deletion=args.prior_deletion,
        ))
